### ISSUE TITLE
Cant install it

### ISSUE THREAD

**Issue by grinb** [howardjohn/kubectl-resources#23]
hi,
When try go get -u -v github.com/howardjohn/kubectl-resources
got this error:

go/src/k8s.io/client-go/transport/round_trippers.go:70:11: cannot convert klog.V(9) (type klog.Verbose) to type bool
go/src/k8s.io/client-go/transport/round_trippers.go:72:11: cannot convert klog.V(8) (type klog.Verbose) to type bool
go/src/k8s.io/client-go/transport/round_trippers.go:74:11: cannot convert klog.V(7) (type klog.Verbose) to type bool
go/src/k8s.io/client-go/transport/round_trippers.go:76:11: cannot convert klog.V(6) (type klog.Verbose) to type bool

go version go1.13.3 darwin/amd64

**Comment by howardjohn** [comment]
Sorry about that, the command should not include `-u`. I changed the readme and made some changes that should make this more stable. Please try it out with `go get github.com/howardjohn/kubectl-resources`
